# -*- coding: utf-8 -*-
"""BrainTumourClassificationAndLLMExplination

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqRF_tANvcvg0jwGm4asxaIu0MiPDxFH
"""

import os
from PIL import Image
import numpy as np
import cv2
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision.io import decode_image
from torchvision.transforms import v2

"""Import Dataset from Drive"""

listOfImagesTrain = []
listOfLabelsTrain = []
listOfImagesTest = []
listOfLabelsTest = []

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Train/notumor/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTrain.append(path)
  listOfLabelsTrain.append(0)
  #break

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Train/meningioma/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTrain.append(path)
  listOfLabelsTrain.append(1)

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Train/glioma/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTrain.append(path)
  listOfLabelsTrain.append(2)

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Train/pituitary/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTrain.append(path)
  listOfLabelsTrain.append(3)


paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Test/notumor/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTest.append(path)
  listOfLabelsTest.append(0)

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Test/meningioma/"


for path in os.listdir(paths):
  path = paths+path
  listOfImagesTest.append(path)
  listOfLabelsTest.append(1)

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Test/glioma/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTest.append(path)
  listOfLabelsTest.append(2)

paths = "/content/drive/MyDrive/Epic and CSCR hospital Dataset/Test/pituitary/"

for path in os.listdir(paths):
  path = paths+path
  listOfImagesTest.append(path)
  listOfLabelsTest.append(3)

"""Custom Dataset  / DataLoader"""

transform = v2.Compose([
    v2.Resize((224, 224)),
    v2.ToTensor()
])

class MRIImages(Dataset):
    def __init__(self, listOfImages, listOfLabels, train=True, transform=transform):
        self.listOfImages = listOfImages
        self.listOfLabels = listOfLabels
        self.transform = transform

    def __len__(self):
        return len(self.listOfImages)

    def __getitem__(self, idx):
        image = Image.open(self.listOfImages[idx]).convert("RGB")
        label = self.listOfLabels[idx]
        if self.transform:
          image = self.transform(image)
        return image, label

datasetImagesAndLabels = MRIImages(listOfImagesTrain, listOfLabelsTrain)
trainLoader = DataLoader(datasetImagesAndLabels, batch_size=64, shuffle=True)

datasetImagesAndLabels = MRIImages(listOfImagesTest, listOfLabelsTest)
testLoader = DataLoader(datasetImagesAndLabels, batch_size=64, shuffle=True)

for images, labels in trainLoader:
  print(images.shape)
  print(labels)
